# Autostart Applications for Sway

# Clipboard Manager
exec --no-startup-id wl-paste -t text --watch clipman store --no-persist

# Automatic screen temperature adjustment (wlsunset)
exec --no-startup-id wlsunset -l 51.5 -L -0.1

# Workstyle - Dynamically renames workspaces to indicate which programs are running 
exec --no-startup-id workstyle &> /tmp/workstyle.log

# Wallpaper Daemon (wpaperd)
exec --no-startup-id wpaperd

# Notification Daemon (mako)
exec --no-startup-id mako

# Alacritty with Zellij - A terminal multiplexer
exec --no-startup-id alacritty --class=scratchpad-terminal -e zellij

# Swayidle for screen locking and suspend
#exec --no-startup-id swayidle -w \
#    timeout 300 'swaylock -f -c 000000' \
#    timeout 1800 'swaymsg "output * dpms off" && systemctl suspend' \
#    resume 'swaymsg "output * dpms on"' \
#    before-sleep 'swaylock -f -c 000000'

# Bluetooth Manager Applet (blueman-applet)
exec --no-startup-id blueman-applet
